### ISSUE TITLE
Routes potentially could lock someone

### ISSUE THREAD

**Issue by cesarwelch** [CodeX-Academy-Official/codex.academy#66]
This might be nit picking, but if I enter a invalid route, it get stuck forever, and even changing the URL is hard because it keeps refreshing, the site need an "Error page" for this cases. 

works in all devices, any browser.

Steps to reproduce:

1. go to the codex site, but use another route that isn't valid for example: http://codex.academy/testlol

https://recordit.co/aRq6iHY3wT

**Comment by bsommardahl** [comment]
I'll let this one live, mainly because we will enable history mode someday soon and this will either change or be fixed automatically.
