### ISSUE TITLE
UI-NodeJS icon Iphone/Mac Safari

### ISSUE THREAD

**Issue by marcomatutehn** [CodeX-Academy-Official/codex.academy#67]
Bug Name: UI-NodeJS icon Iphone/Mac Safari
Reported By: Marco Martinez
Environment: Mac OS

Description:
The icon doesn't show correctly.

Steps To Reproduce:
1) Open URL https://www.codex.academy/#/howitworks#tech
2) Navigate to the KNOWLEDGE IS POWER section.
3) Icon shows appear correctly

Expected Result: Show correctly icon.

Node Js icon on Safari Version 13.0.5 (15608.5.11)
Also in Safari for Iphone

<img width="501" alt="Screen Shot 2020-04-10 at 21 03 20" src="https://user-images.githubusercontent.com/21376011/79033910-596b1e00-7b6f-11ea-9b3b-857cccb8604a.png">

![IMG_2157](https://user-images.githubusercontent.com/21376011/79033945-9d5e2300-7b6f-11ea-9549-3a88474b43e2.PNG)
 6.

**Comment by bsommardahl** [comment]
Great catch. This is fixed.
