### ISSUE TITLE
Social media Icon not aligned in mobile view. 

### ISSUE THREAD

**Issue by cesarwelch** [CodeX-Academy-Official/codex.academy#70]
Android phone latest version.
Chrome for mobile: 80.0.3987.162

Steps to reproduce: 

- Enter the Codex Site

- Scroll down to the footer section

- Social media icons are not aligned.

![image](https://user-images.githubusercontent.com/7519893/79034085-8f5cd200-7b70-11ea-9d32-a33b0c75a0b2.png)

**Comment by bsommardahl** [comment]
Great catch,. This is fixed.
