### ISSUE TITLE
UI recommendation for "findplan"

### ISSUE THREAD

**Issue by cesarwelch** [CodeX-Academy-Official/codex.academy#78]
Not an issue, but an UX/UI recommendation, in this section when I'm on a mobile, I'm not sure what's happening, I just click in the button "Select" button and nothing happen. there not enough visual cues to know what happened.

this could definitely be confusing. 

https://recordit.co/ertbyubWhz

**Comment by bsommardahl** [comment]
This is a really good find. I never thought about the need to scroll down on click on that screen!
