### ISSUE TITLE
Banner time depends on PC timezone.

### ISSUE THREAD

**Issue by cesarwelch** [CodeX-Academy-Official/codex.academy#79]
Not sure if intended, but the banner show different time depending on the timezone of each pc. 
[image1](https://user-images.githubusercontent.com/7519893/79035380-2f1f5d80-7b7b-11ea-9e16-4a8340c18b1f.png)
[image2](http://prntscr.com/rx5dgm)

I take both at the same time, one through browserstack with a PC on US, and another one with mine.
Once again this could be inteded but might be problems in logs if the system has this discrepancy.

**Comment by bsommardahl** [comment]
Fixed.
